FROM node:20

# 1. Системные зависимости
RUN apt-get update && \
    apt-get install -y python3 make g++ && \
    rm -rf /var/lib/apt/lists/*

# 2. Рабочая директория
WORKDIR /app

# 3. Копируем package.json для кэширования слоя
COPY package.json ./
COPY backend/package*.json ./backend/
COPY shared/package*.json ./shared/

# 4. Глобальные утилиты
RUN npm install -g @nestjs/cli

# 5. Копируем исходники и entrypoint
COPY ./shared ./shared
COPY ./backend ./backend
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# 6. Рабочая директория для backend
WORKDIR /app/backend

# 7. Используем entrypoint
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /app/backend
